services:
  web:
    build: .
    volumes: 
      - .:/app
    ports:
      - "80:80"
    env_file: ".env"
    networks:
      - fastapi-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:12.5

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 4
      start_period: 30s
      timeout: 10s

    volumes:
      - postgres_data:/var/lib/postgresql/data/

    env_file:
      - ./postgres.env
    ports:
      - "5432:5432"
    networks:
      - fastapi-network

networks:
  fastapi-network:
    driver: bridge

volumes:
  postgres_data:

